### ISSUE TITLE
дополнительный функционал закрытия окон

### ISSUE THREAD

**Issue by efimovpedan** [touch451/MyWindows#12]
добавить в скрипт Window необязательные параметры, которые можно менять на префабе:
1. закрытие окна по тапу в любую область вне окна
2. закрытие окна по нажатию системной кнопки "back" `if (Input.GetKey(KeyCode.Escape))` для ПК это нажатие esc, для телефонов это стрелка назад или домой. Учесть, что если открыто несколько окон, то должно закрыться последнее

**Comment by touch451** [comment]
Доработка добавлена в develop

**Comment by efimovpedan** [comment]
> Доработка добавлена в develop

тк изменения были залиты не через pull request, то пришлось создать новые задачи
1) https://github.com/touch451/MyWindows/issues/18
2) https://github.com/touch451/MyWindows/issues/19
3) https://github.com/touch451/MyWindows/issues/20
4) https://github.com/touch451/MyWindows/issues/21

лучше заливать все изменения в develop и master через pull request отдельных веток. тогда можно будет привязывать комментарии прям к  запросу на слияние и править до того как изменения уже попадут в стабильные ветки
