### ISSUE TITLE
Событие закрытие окна можно сделать не статичным и подписываться на событие будет Window, а не Controller

### ISSUE THREAD

**Issue by efimovpedan** [touch451/MyWindows#18]
https://github.com/touch451/MyWindows/blob/1948a5a4b9894bd34d1ab4e0b14e1673b453b9df/Assets/Scripts/Background.cs#L9

Это позволит избавиться от функции CloseWindowOnTapBackground в классе WindowController. 
Не нужно будет искать окно в массиве и получать ссылку на окно через GetComponent<Window> тк работать с BackGround будет сам Window. 
Сейчас получается что WindowController имеет ссылку на Background, он вызывает функцию на WindowController, потом контроллер обращается в Window и проигрывает анимацию. 

По-хорошему лучше у экземпляров вообще не использовать статичные события.

Код инициализации background в классе Window будет выглядить так:
```
[SerializeField] private Background background = null;
    private void InitBackGround()
    {
        if (optionCloseWindowOnTap)
        {
            if (background != null)
            {
                background.OnTap += CloseWindow;
            }
            else
            {
                throw new UnityException("missing reference. the window needs a background component");
            }
        }
    }

    private void Awake()
    {
        closeButton.onClick.AddListener(() => CloseWindow());
        InitBackGround();
    }

```

Так как окно может удалиться со сцены, не забыть отписаться от события в OnDestroy функции

Дополнительно, можно избавится от поля [SerializeField] private Background background = null и добавления бекграунда в редакторе у префаба в ручную и автоматизировать этот процесс; 
Смотрим в момент инициализации если optionCloseWindowOnTap == true, тогда в корне окна спавним background из ресурса и сразу получаем на него ссылку.

**Comment by touch451** [comment]
Не получилось выполнить. Если спавнить background в корне окна, то он растягивается по размеру окна, а не по размеру Canvas'а (не на весь экран). А если спавнить в корень Canvas'a, то он растягивается на весь экран, но перекрывает кнопки. 
Решил сделать так же как и CloseWindowOnInputKeyBack.
