### ISSUE TITLE
Можно хранить окна в массиве как тип Window, а не GameObject

### ISSUE THREAD

**Issue by efimovpedan** [touch451/MyWindows#19]
https://github.com/touch451/MyWindows/blob/1948a5a4b9894bd34d1ab4e0b14e1673b453b9df/Assets/Scripts/ControllersAndManages/WindowsController.cs#L12

Сейчас при каждом получении окна в функции TryGetCurOpenWindow возвращается GameObject и далее приходится получать компонент Window через objWindow.GetComponent<Window>();. Проще один раз сделать GetComponent в момент загрузки из ресурса и сохранить окно в массив, чем делать GetComponent  при каждой работе с окном.

1) Переделать массив окон c GameObject на Window
2) GetWindowByWindowType сделать получение компонента Window из того что вернул ResourceController. Сразу можно бросить UnityException, если на объекте окна отсутствует компонент Window
3) везде, где используется window как GameObject, поменять тип на Window

**Comment by touch451** [comment]
Выполнено.
