### ISSUE TITLE
добавить в функцию "открыть окно" параметр "какое окно должно открыться"

### ISSUE THREAD

**Issue by efimovpedan** [touch451/MyWindows#2]
в Assets/Scripts/WindowsController.cs

**Comment by touch451** [comment]
Выполнено в коммите от 18.09.2020

**Comment by efimovpedan** [comment]
https://github.com/touch451/MyWindows/blob/cc492cf7b83a39956695c57bb8247923fdbf6d15/Assets/Scripts/UIButton.cs#L24
функция должна принимать параметр windowType, тогда получение окна и проверка "удалось ли найти окно" переедет внутрь этой функции.

Все проверки и получение необходимых ресурсов нужно держать внутри контроллеров, а кнопка должна только вызывать функцию на контроллере
