### ISSUE TITLE
некоторые члены используется только внутри класса WindowController или нарушают принцип инкапсуляции

### ISSUE THREAD

**Issue by efimovpedan** [touch451/MyWindows#21]
https://github.com/touch451/MyWindows/blob/1948a5a4b9894bd34d1ab4e0b14e1673b453b9df/Assets/Scripts/ControllersAndManages/WindowsController.cs#L6

можно закрыть модификатором private
1) `public void CloseWindowOnInputKeyBack()` - его вызывает подписка на событие 
2) `TryGetCurOpenWindow` - используется только для логики контроллера
3) `GetWindowByWindowType` используется только для инициализации контроллера

Массив openWindowsList, доступен для изменения в других классах. Нужно его закрыть модификатором private и реализовать функцию в WindowController, которая будет удалять закрывающееся окно из массива

**Comment by touch451** [comment]
Выполнено. TryGetCurOpenWindow  оставил public, т.к. используется в Window.
