### ISSUE TITLE
реализовать смену сцен

### ISSUE THREAD

**Issue by efimovpedan** [touch451/MyWindows#4]
предполагается, что WindowsController может открыть окно в любой момент и на любой сцене

**Comment by touch451** [comment]
Выполнено в коммите от 18.09.2020

**Comment by efimovpedan** [comment]
логику из функции https://github.com/touch451/MyWindows/blob/cc492cf7b83a39956695c57bb8247923fdbf6d15/Assets/Scripts/UIButton.cs#L33

лучше перенести в ScenesController. тогда функция   SceneController.Instance.LoadScene(sceneType) будет принимать не string, а тип сцены

Если в будущем будет еще одна кнопка для открытия других сцен, то не придется дублировать код получения имени сцены по типу сцены и дублировать проверку найдена ли сцена.
