### ISSUE TITLE
необходим рефакторинг для WindowsController

### ISSUE THREAD

**Issue by efimovpedan** [touch451/MyWindows#5]
- [x] WindowsController не должен знать ничего про анимацию текущего открыто окна, работу с анимацией нужно перенести в класс Window

- [x] WindowsController не должен уметь закрывать текущее окно, функцию закрытия нужно реализовать внутри класса Window. Тогда у кнопки крестика мы сможем указать эту функцию закрытия

**Comment by touch451** [comment]
Выполнено в коммите от 18.09.2020

**Comment by efimovpedan** [comment]
https://github.com/touch451/MyWindows/blob/cc492cf7b83a39956695c57bb8247923fdbf6d15/Assets/Scripts/Window.cs#L21
можно заменить на 
`GetComponent<Animator>().SetTrigger("Close");`
